/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppLogPumpingRouteImport } from './routes/_app.log.pumping'
import { Route as AppLogNursingRouteImport } from './routes/_app.log.nursing'
import { Route as AppLogDiaperRouteImport } from './routes/_app.log.diaper'
import { Route as AppLogBottleRouteImport } from './routes/_app.log.bottle'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLogPumpingRoute = AppLogPumpingRouteImport.update({
  id: '/log/pumping',
  path: '/log/pumping',
  getParentRoute: () => AppRoute,
} as any)
const AppLogNursingRoute = AppLogNursingRouteImport.update({
  id: '/log/nursing',
  path: '/log/nursing',
  getParentRoute: () => AppRoute,
} as any)
const AppLogDiaperRoute = AppLogDiaperRouteImport.update({
  id: '/log/diaper',
  path: '/log/diaper',
  getParentRoute: () => AppRoute,
} as any)
const AppLogBottleRoute = AppLogBottleRouteImport.update({
  id: '/log/bottle',
  path: '/log/bottle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/log/bottle': typeof AppLogBottleRoute
  '/log/diaper': typeof AppLogDiaperRoute
  '/log/nursing': typeof AppLogNursingRoute
  '/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/log/bottle': typeof AppLogBottleRoute
  '/log/diaper': typeof AppLogDiaperRoute
  '/log/nursing': typeof AppLogNursingRoute
  '/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/log/bottle': typeof AppLogBottleRoute
  '/_app/log/diaper': typeof AppLogDiaperRoute
  '/_app/log/nursing': typeof AppLogNursingRoute
  '/_app/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/register'
    | '/log/bottle'
    | '/log/diaper'
    | '/log/nursing'
    | '/log/pumping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/register'
    | '/log/bottle'
    | '/log/diaper'
    | '/log/nursing'
    | '/log/pumping'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/onboarding'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/log/bottle'
    | '/_app/log/diaper'
    | '/_app/log/nursing'
    | '/_app/log/pumping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/pumping': {
      id: '/_app/log/pumping'
      path: '/log/pumping'
      fullPath: '/log/pumping'
      preLoaderRoute: typeof AppLogPumpingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/nursing': {
      id: '/_app/log/nursing'
      path: '/log/nursing'
      fullPath: '/log/nursing'
      preLoaderRoute: typeof AppLogNursingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/diaper': {
      id: '/_app/log/diaper'
      path: '/log/diaper'
      fullPath: '/log/diaper'
      preLoaderRoute: typeof AppLogDiaperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/bottle': {
      id: '/_app/log/bottle'
      path: '/log/bottle'
      fullPath: '/log/bottle'
      preLoaderRoute: typeof AppLogBottleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLogBottleRoute: typeof AppLogBottleRoute
  AppLogDiaperRoute: typeof AppLogDiaperRoute
  AppLogNursingRoute: typeof AppLogNursingRoute
  AppLogPumpingRoute: typeof AppLogPumpingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppLogBottleRoute: AppLogBottleRoute,
  AppLogDiaperRoute: AppLogDiaperRoute,
  AppLogNursingRoute: AppLogNursingRoute,
  AppLogPumpingRoute: AppLogPumpingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
