/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppGrowthRouteImport } from './routes/_app.growth'
import { Route as AppChartsRouteImport } from './routes/_app.charts'
import { Route as AppLogPumpingRouteImport } from './routes/_app.log.pumping'
import { Route as AppLogNursingRouteImport } from './routes/_app.log.nursing'
import { Route as AppLogNoteRouteImport } from './routes/_app.log.note'
import { Route as AppLogGrowthRouteImport } from './routes/_app.log.growth'
import { Route as AppLogDiaperRouteImport } from './routes/_app.log.diaper'
import { Route as AppLogBottleRouteImport } from './routes/_app.log.bottle'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRoute,
} as any)
const AppLogPumpingRoute = AppLogPumpingRouteImport.update({
  id: '/log/pumping',
  path: '/log/pumping',
  getParentRoute: () => AppRoute,
} as any)
const AppLogNursingRoute = AppLogNursingRouteImport.update({
  id: '/log/nursing',
  path: '/log/nursing',
  getParentRoute: () => AppRoute,
} as any)
const AppLogNoteRoute = AppLogNoteRouteImport.update({
  id: '/log/note',
  path: '/log/note',
  getParentRoute: () => AppRoute,
} as any)
const AppLogGrowthRoute = AppLogGrowthRouteImport.update({
  id: '/log/growth',
  path: '/log/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppLogDiaperRoute = AppLogDiaperRouteImport.update({
  id: '/log/diaper',
  path: '/log/diaper',
  getParentRoute: () => AppRoute,
} as any)
const AppLogBottleRoute = AppLogBottleRouteImport.update({
  id: '/log/bottle',
  path: '/log/bottle',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/charts': typeof AppChartsRoute
  '/growth': typeof AppGrowthRoute
  '/history': typeof AppHistoryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/log/bottle': typeof AppLogBottleRoute
  '/log/diaper': typeof AppLogDiaperRoute
  '/log/growth': typeof AppLogGrowthRoute
  '/log/note': typeof AppLogNoteRoute
  '/log/nursing': typeof AppLogNursingRoute
  '/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/charts': typeof AppChartsRoute
  '/growth': typeof AppGrowthRoute
  '/history': typeof AppHistoryRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/log/bottle': typeof AppLogBottleRoute
  '/log/diaper': typeof AppLogDiaperRoute
  '/log/growth': typeof AppLogGrowthRoute
  '/log/note': typeof AppLogNoteRoute
  '/log/nursing': typeof AppLogNursingRoute
  '/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/charts': typeof AppChartsRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/log/bottle': typeof AppLogBottleRoute
  '/_app/log/diaper': typeof AppLogDiaperRoute
  '/_app/log/growth': typeof AppLogGrowthRoute
  '/_app/log/note': typeof AppLogNoteRoute
  '/_app/log/nursing': typeof AppLogNursingRoute
  '/_app/log/pumping': typeof AppLogPumpingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/growth'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/login'
    | '/register'
    | '/invite/$token'
    | '/log/bottle'
    | '/log/diaper'
    | '/log/growth'
    | '/log/note'
    | '/log/nursing'
    | '/log/pumping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/growth'
    | '/history'
    | '/onboarding'
    | '/settings'
    | '/login'
    | '/register'
    | '/invite/$token'
    | '/log/bottle'
    | '/log/diaper'
    | '/log/growth'
    | '/log/note'
    | '/log/nursing'
    | '/log/pumping'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/charts'
    | '/_app/growth'
    | '/_app/history'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/_auth/login'
    | '/_auth/register'
    | '/invite/$token'
    | '/_app/'
    | '/_app/log/bottle'
    | '/_app/log/diaper'
    | '/_app/log/growth'
    | '/_app/log/note'
    | '/_app/log/nursing'
    | '/_app/log/pumping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charts': {
      id: '/_app/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/pumping': {
      id: '/_app/log/pumping'
      path: '/log/pumping'
      fullPath: '/log/pumping'
      preLoaderRoute: typeof AppLogPumpingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/nursing': {
      id: '/_app/log/nursing'
      path: '/log/nursing'
      fullPath: '/log/nursing'
      preLoaderRoute: typeof AppLogNursingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/note': {
      id: '/_app/log/note'
      path: '/log/note'
      fullPath: '/log/note'
      preLoaderRoute: typeof AppLogNoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/growth': {
      id: '/_app/log/growth'
      path: '/log/growth'
      fullPath: '/log/growth'
      preLoaderRoute: typeof AppLogGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/diaper': {
      id: '/_app/log/diaper'
      path: '/log/diaper'
      fullPath: '/log/diaper'
      preLoaderRoute: typeof AppLogDiaperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log/bottle': {
      id: '/_app/log/bottle'
      path: '/log/bottle'
      fullPath: '/log/bottle'
      preLoaderRoute: typeof AppLogBottleRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChartsRoute: typeof AppChartsRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLogBottleRoute: typeof AppLogBottleRoute
  AppLogDiaperRoute: typeof AppLogDiaperRoute
  AppLogGrowthRoute: typeof AppLogGrowthRoute
  AppLogNoteRoute: typeof AppLogNoteRoute
  AppLogNursingRoute: typeof AppLogNursingRoute
  AppLogPumpingRoute: typeof AppLogPumpingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChartsRoute: AppChartsRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppLogBottleRoute: AppLogBottleRoute,
  AppLogDiaperRoute: AppLogDiaperRoute,
  AppLogGrowthRoute: AppLogGrowthRoute,
  AppLogNoteRoute: AppLogNoteRoute,
  AppLogNursingRoute: AppLogNursingRoute,
  AppLogPumpingRoute: AppLogPumpingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
